[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'

[flake8]
max-line-length = 88
extend-ignore = "E203, W503"
per-file-ignores = "__init__.py: F401"
